# Site settings
locale: "en-US"
title: "Sitebase"
title_separator: "-"
email: wim@sitebase.be
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.sitebase.be" # the base hostname & protocol for your site
disqus_shortname: sitebase
twitter_username: sitebase
github_username:  sitebase

# Build settings
timezone:    Europe/Brussels
future:      true
highlighter: rouge
markdown: kramdown
plugins:
  - jekyll-paginate

# Amount of post to show on home page
paginate: 5

# SEO
permalink: /:title/
excerpt_separator: "\n\n"
google_site_verification : "pd5IFRm5_vyJUrqWK5fCJz2fIS5qO_9w3svIS4jVJVg"
google_analytics: "UA-2072779-31"
bing_site_verification   : "652CEB15C63A549789119465E65DC74C"
alexa_site_verification  :
yandex_site_verification : "a1415abd2aeb78f5"

# Social Sharing
twitter:
  username               : "Sitebase"
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : "person"
  name                   : "Wim Mostmans"
  links:
    - "https://twitter.com/sitebase"
    - "https://be.linkedin.com/in/sitebase"
    - "https://www.flickr.com/photos/24652808@N02/"
    - "http://stackoverflow.com/users/776272/wim-mostmans"
    - "https://www.instagram.com/sitebase/"

# Site Author
author:
  name             : "Wim Mostmans"
  avatar           : "avatar-wim.jpg"
  bio              : "Freelance developer and Co-founder of <a href='https://www.ambassify.com'>Ambassify</a> with a general interest for web technologies and electronics."
  location         : "Belgium"
  email            : "wim@sitebase.be"
  uri              : "http://sitebase.be"
  bitbucket        :
  codepen          :
  dribbble         :
  facebook         :
  foursquare       :
  github           : "sitebase"
  keybase          : "sitebase"
  instagram        : "sitebase"
  lastfm           :
  linkedin         : "sitebase"
  pinterest        : "sitebase"
  soundcloud       :
  stackoverflow    : "http://stackoverflow.com/users/776272/wim-mostmans"
  steam            :
  tumblr           :
  twitter          : "sitebase"
  vine             :
  weibo            :
  xing             :
  youtube          : "sitebase"

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
